### ISSUE TITLE
Does not work with Docker 1.10

### ISSUE THREAD

**Issue by ghaering** [gondor/docker-volume-netshare#13]
The volumes are missing the Get() and List() methods. Maybe other adjustments are also necessary to work with Docker 1.10.

**Comment by beniwtv** [comment]
Some more debug:

```
$ make
go get
# github.com/gondor/docker-volume-netshare/netshare
netshare/netshare.go:115: cannot use d (type drivers.nfsDriver) as type volume.Driver in argument to start:
        drivers.nfsDriver does not implement volume.Driver (missing Get method)
netshare/netshare.go:123: cannot use d (type drivers.efsDriver) as type volume.Driver in argument to start:
        drivers.efsDriver does not implement volume.Driver (missing Get method)
netshare/netshare.go:134: cannot use d (type drivers.cifsDriver) as type volume.Driver in argument to start:
        drivers.cifsDriver does not implement volume.Driver (missing Get method)
make: *** [deps] Error 2
```

**Comment by gondor** [comment]
Thank you for logging this.  I'll look into this tonight.  Your probably right and 1.10 has added new elements to their API.

**Comment by gondor** [comment]
Ok, changes have been added and Docker 1.10 is now supported.  Also update the binaries for download.  README has new links

**Comment by beniwtv** [comment]
Id does compile now, great!
However, with Docker 1.10.1, wehn running the start command:

`docker run -d -e "SERVICE_NAME=testservice" --restart always -v 192.168.0.1/www/sprenz/sites-enabled:/etc/nginx/sites-enabled -v 192.168.0.1/www/sprenz/www:/var/www...`

Accessing the socket seems to work, though:

```
curl -v --unix-socket /run/docker/plugins/nfs.sock http:/Plugin.Activate
*   Trying /run/docker/plugins/nfs.sock...
* Connected to http (/run/docker/plugins/nfs.sock) port 80 (#0)
> GET /Plugin.Activate HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/vnd.docker.plugins.v1.1+json
< Date: Tue, 16 Feb 2016 13:15:36 GMT
< Content-Length: 33
<
{"Implements": ["VolumeDriver"]}
```

**Comment by gondor** [comment]
I don't see you specifying the volume driver above in your run command.  Also by default it will use unix.sock.  If you want the driver to use tcp then you need to run it with that flag.

**Comment by beniwtv** [comment]
Sorry, I copied the wrong command.I was testing a local directory volume, to see if volumes where working at all on my system with Docker 1.10.1.

So here is the correct command:

`docker run -d -e "SERVICE_NAME=testservice" --restart always --volume-driver=nfs -v 192.168.0.1/www/sprenz/sites-enabled:/etc/nginx/sites-enabled -v 192.168.0.1/www/sprenz/www:/var/www --name testservice -p 80 registry.synergicbee.com/nginx`

**Comment by gondor** [comment]
So I just tested this on CentOS using Docker 1.10.1 and had no issues.    I ran netshare with just the `nfs` argument and nothing else.  Then launched an Ubuntu container with the mount and was able to rw files with no issues.

Are you sure you don't have an old version running? What OS are you running?

**Comment by beniwtv** [comment]
It's Ubuntu 15.10 with Docker 1.10.1. I'll have to do more debug, I found another report for this problem, and it seems something may have to be reset on my side.

**Comment by gondor** [comment]
I'm going to close this for now.  As an additional test I did a fresh install of Ubuntu 15.10, added nfs-commons, docker 1.10.1 and netshare.  Mounted a nfs4 share from another host within an ubuntu docker image with no issues.
